### ISSUE TITLE
Balances should be cached in a HashMap

### ISSUE THREAD

**Issue by dkbay** [lokka30/PhantomEconomy#18]
It'd prolly be beneficial to performance if there was an in memory variable that stored balances and other things and a queue worker that persisted the updates to the flatfiles so we don't need to access a file every time we need to do something

**Comment by lokka30** [comment]
Sounds like a great idea, would storing the balance in a hashmap suit this issue?

**Comment by dkbay** [comment]
Yep hashmap should work fine as long as you update the hash map every time you set or update the balance and also push the update to the queue 

I'm not sure if it'll be best to load all players balances on enable or as they're being accessed

**Comment by lokka30** [comment]
Awesome.
I'll be adding the balance to the cache when the players join :)

**Comment by lokka30** [comment]
I've implemented this issue into the upcoming release.
* When a player joins, the plugin gets the balance from the data file and puts it into a HashMap
* When the getBalance method is requested, it prefers to return the value that is inside the HashMap
* When the withdrawPlayer or depositPlayer method is successful, the new balance will be replaced in the HashMap
* When the player leaves, their balance is removed from the HashMap (in case a masive hashmap is created by a large server which never restarts)

I'll close the issue. If I haven't done something right or I should expand on it, please reopen the issue.
Cheers
