### ISSUE TITLE
Error when trying to perform actions on player with /eco or /pay

### ISSUE THREAD

**Issue by Tonin386** [lokka30/PhantomEconomy#19]
When I try to use one of the following command, whatever the playername name is and even if this one is online on the server I get the error "PLAYER hasn't joined the server before"
- pay PLAYER
- eco add/reset/set/take PLAYER 50

**Comment by lokka30** [comment]
Are you sure you are using the exact (case sensitive) username of the player you are trying to interact with? Through my brief testing I didn't run into this issue.

**Comment by lokka30** [comment]
@Tonin386 Is your server running in offline mode?

**Comment by lokka30** [comment]
fixed in 1.6-release build 4
