### ISSUE TITLE
Data is not kept upon restart

### ISSUE THREAD

**Issue by CACGaming** [lokka30/PhantomEconomy#23]
When the server that is running the plugin is restarted the balance does not save properly. It makes 2 (sort of) identical users and updates the balance of what is supposed to be the correct one but doesn't read that number.

Ex. (My data.json)
{
   "players": {
      "%id%": {"balance": 51},                          <--- this updates but gets reset upon server restart.
      "%id%,balance": 50
   },
   "file-version": 1
}

**Comment by CACGaming** [comment]
I managed to fix it. I assume you had a mistype. In JoinListener.java line 20 character 84 what is supposed to be a period(.) is accidentally a comma(,)

Attached is the fixed file (As a zip due to github limitations):
[JoinListener.zip](https://github.com/lokka30/PhantomEconomy/files/4435838/JoinListener.zip)

**Comment by lokka30** [comment]
Thanks a lot! Will look at this now

**Comment by lokka30** [comment]
Issue resolved in the upcoming release 1.7-RELEASE
Cheers
