### ISSUE TITLE
Support cracked servers

### ISSUE THREAD

**Issue by plebexer** [lokka30/PhantomEconomy#32]
Hey! i installed recently the plugin and everything was working fine until i realized something, money from my players was dissappearing, and then i realized that the plugin uses uuids to store the money, and the problem is that my server is No Premium, because im from argentina and most of the players here dont have minecraft premium, so i want to ask if you could please add so the storage also saves players names and not only uuids, because some players are loosing money.

**Comment by lokka30** [comment]
Sorry plebexer! I will not be supporting cracked servers unless they can effectively use the UUID system. 😞
