### ISSUE TITLE
add /reload

### ISSUE THREAD

**Issue by bnjrKemal** [lokka30/PhantomEconomy#34]
I did not see the reload command for this plugin, if it does not, need to be added.

**Comment by lokka30** [comment]
> 
> 
> I did not see the reload command for this plugin, if it does not, need to be added.

PhantomEconomy 1.x reloads everything for you completely automatically! 😁 

However, in the upcoming PhantomEconomy v2, file settings will be stored in memory for much better performance, so there will be a reload command in that version.

**Comment by bonjourkemal** [comment]
can you send me a link? i can't found
