### ISSUE TITLE
[v2] Banks!

### ISSUE THREAD

**Issue by lokka30** [lokka30/PhantomEconomy#40]
DrWurzeli said in the ticket which he requested the feature:

> Claims in GD have a unique UUID that bank accounts can be tied to. If supported by the economy plugin, that claim creates a public account that players can access with GD commands to withdraw and deposit money
> (really nice for town claims where people can use it to store town funds and stuff or just people wanting to store some money in case they lose it on death).
> 
> this would also - much as in phantombank - enable the option - for all other plugins using PhantomEco - of mapping virtual accounts to players resulting in having more than 1 bank account per user. to differentiate, a flag/label could be added for virtual accounts so the eco plugin knows which accounts are virtual ones tied to UUIDs of objects and which are linked to player UUIDs.

**Comment by DrWurzeli** [comment]
thanks for adding :)
Supporting virtual accounts from the VaultAPI would be much appreciated.

**Comment by lokka30** [comment]
Progress has started but I am too unfamiliar with Vault's bank system to continue developing it.

**Comment by lokka30** [comment]
Completed, needs testing. Issue will be closed as this is definitely being added in v2.0.0.
See [this](https://github.com/lokka30/PhantomEconomy/blob/master/src/main/java/io/github/lokka30/phantomeconomy_v2/what_is_this.txt) for more information.
