### ISSUE TITLE
[v2] Placeholders 

### ISSUE THREAD

**Issue by Martinko366** [lokka30/PhantomEconomy#41]
Are there any placeholders that I can use for scoreboard? Thanks!

**Comment by lokka30** [comment]
Not at the moment. will be added in version 2.0.0 :)

**Comment by lokka30** [comment]
> Are there any placeholders that I can use for scoreboard? Thanks!

I forgot to mention - if you only want to display the player's balance, see PlaceholderAPI's Vault placeholders! :)

Full PlaceholderAPI placeholders will be added in the next version I think
See https://github.com/lokka30/PhantomEconomy/blob/master/src/main/java/io/github/lokka30/phantomeconomy_v2/what_is_this.txt for more information
