### ISSUE TITLE
Daily Payments?

### ISSUE THREAD

**Issue by Lucario1217** [lokka30/PhantomEconomy#42]
I was thinking, would it be possible to add an option, to give a daily amount of money to everyone in the server? I made a town where everyone gets an allowance everyday, and it gets quite annoying to do every single one, one at a time.

**Comment by lokka30** [comment]
Hi @Lucario1217, thanks for the feature request. Although it is a good idea, I won't be adding it in PhantomEconomy as the plugin is simply a *core* for all other Vault-hooking plugins to use. I would point you to find a plugin which can offer daily payments that hooks into Vault.

I won't add such features to PE as I want to keep it as simple and bulletproof as possible, so I only want to add what is absolutely required to function effectively.
