### ISSUE TITLE
Permissions not work

### ISSUE THREAD

**Issue by franciscomirasg** [lokka30/PhantomEconomy#44]
I am using vault, phantomEconomy and lucky permissions (a permissions plugin). I have the group admin and I add te permission: phantomeconomy.* to the group. I restart the server and I can't use any command except money, baltop and pay.

**Comment by lokka30** [comment]
Thanks for the report @franciscomirasg, I will look into this now.

**Comment by lokka30** [comment]
I have checked the `plugin.yml` file of my plugin, and it appears that all of the permissions are added under `phantomeconomy.*`. Please check your permissions configuration again. You should have access to:
* `/economy`,
* `/balance`,
* `/balance [player]`,
* `/pay`,
* `/baltop`,
* and `/phantomeconomy backup`.

Please state if it appears that it is actually a fault with the plugin - if so, i'll investigate once more.

**Comment by lokka30** [comment]
Issue will be closed if a response has not been made within 2 weeks (14 days) since the original post.

**Comment by franciscomirasg** [comment]
Sorry, for submit the issue, I check the permissions and the phantomeconomy.* was bad written.
Great work, I like your plugin.

**Comment by lokka30** [comment]
Thanks @franciscomirasg :) Glad you got it solved.
