### ISSUE TITLE
Towny not working

### ISSUE THREAD

**Issue by Verdillian** [lokka30/PhantomEconomy#48]
Towny lists that the town has the money in the bank but then gives an error saying to do /t withdraw -5208 or whatever the towns balance is. This started happening when I switched to this economy plugin.

**Comment by lokka30** [comment]
Please provide more information

**Comment by Verdillian** [comment]
I don’t really have much information but I imagine it was related to me using a pre release version of towny as switching to the latest release worked perfectly.

**Comment by lokka30** [comment]
> 
> 
> I don’t really have much information but I imagine it was related to me using a pre release version of towny as switching to the latest release worked perfectly.

Okay, thank you for noting that. Please do not use pre-release versions of software unless you are comfortable with receiving bugs of any caliber. :)
