### ISSUE TITLE
Bug with Messages

### ISSUE THREAD

**Issue by OfficialTheosis** [lokka30/PhantomEconomy#53]
I've found two bugs regarding messages.yml. The first is that the string "invalid-number-zero" doesn't seem to correctly replace "%number%" with the number the player wrote. This screenshot shows an example:
![1](https://user-images.githubusercontent.com/26799016/87888139-bd309d00-ca22-11ea-8cf4-f39ecd5d59b7.png)

The second is that there is an uncustomisable message that is shown when a player tries to pay another player an amount which is a string rather than a number. This screenshot shows an example where I tried to pay my alternate account "this_is_a_test":
![2](https://user-images.githubusercontent.com/26799016/87888158-ed783b80-ca22-11ea-811c-46a1e53d2068.png)

Would be nice if the first bug was fixed and the message shown in the second screenshot becomes customisable. :)

**Comment by lokka30** [comment]
About 60% into completely redoing phantomeconomy :)

Issue will be resolved in that release, although it may take a while.

In the first screenshot, it's as simple as me forgetting to replace `%number%`. In the second screenshot, I have told the plugin to look for a path in the `messages.yml` which doesn't exist - highly likely to be a typo in there.

Thanks for opening the issue :)
