### ISSUE TITLE
[Feature Request] Add /paytoggle command

### ISSUE THREAD

**Issue by OfficialTheosis** [lokka30/PhantomEconomy#54]
So basically players would be able to run /paytoggle and it would disable or enable their ability to be paid by other players. This could stop payment spams (e.g. typing "/pay <player> 0.01" repeatedly) and could also be used by players who don't want help from other players.

**Comment by lokka30** [comment]
Great idea! I'll make it an argument for `/pay`, e.g. `/pay toggle`.

**Comment by OfficialTheosis** [comment]
Not sure if having arguments after `/pay` is the best idea in case the rare occurrence of a player with a username matching the argument happens. :p

**Comment by lokka30** [comment]
Although I could argue that paying users actually requires two arguments, I could see confusion being caused if a user named `toggle` has joined the server before. I'll go with your `/paytoggle` idea. :)

**Comment by lokka30** [comment]
I'll close this issue since it's going to be added in the v2.0.0 update. It's in the todo list here:
https://github.com/lokka30/PhantomEconomy/blob/master/src/main/java/io/github/lokka30/phantomeconomy_v2/what_is_this.txt
