### ISSUE TITLE
Make paying offline players configurable

### ISSUE THREAD

**Issue by OfficialTheosis** [lokka30/PhantomEconomy#55]
I'm not sure how useful this would be in general, but I'm sure it would be useful for some, including myself. We should be able to configure whether or not paying offline players is possible.

Basically, on my server I have it so that people can't pay players who are a lower rank than them, and this is done through a plugin I made which checks their LuckPerms groups and either denies or allows the payment accordingly. However, I've just realised that this breaks when the target player is offline, because I cannot check their LuckPerms group (since it is done using the Player#hasPermission method, and this method does not exist for OfflinePlayer).

Like I said, I'm not sure how useful this would be for most people, but I hope it can be added. :)

**Comment by TheosisOfficial** [comment]
Never mind, this can be removed. :)

**Comment by OfficialTheosis** [comment]
Disregard this. :)
